[45기 문승종] addCart, getCart, updateOrderStatus function
wecode-bootcamp-korea/45-1st-TRES-backend pull request #13
Opened 2023-05-07 05:25 UTC by msj102525

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
장바구니에 원하는 상품을 담아 놔서 굳이 기억하지 않고 있어도 나중에 한번에 확인을 할 수 있습니다. 

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

여러가지 제품을 원하는 만큼 한번에 구매 할 수 있습니다.

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.

- addCart : cart에 상품 담기
- getCart : 장바구니 클릭시 담아놨던 정보 가져오기
- updateOrderStatus : 주문 완료시 incart였던 status_code를 배송중 status로 바꾸기(배송중 또는 주문했던 내역을 가져올수 있다 하지만 기능 구현 X)

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
<br />
장바구니 가져오기
![getCart](https://user-images.githubusercontent.com/95277177/236659123-97af13be-9352-4dec-8b94-8f2c1de605b6.png)
44번 유저 결제 완료 전
![beforeUpdateStatus](https://user-images.githubusercontent.com/95277177/236659340-79dcafdc-0ac6-49d9-bf2f-2e2431ac0409.png)
44번 유저 결제 완료  후
![updateStatusPostman](https://user-images.githubusercontent.com/95277177/236659353-8c594918-a86d-41c8-a7a0-5707f18d6c7d.png)

![afterUpdateStatus](https://user-images.githubusercontent.com/95277177/236659349-2b2db2fd-94d2-4242-b4e9-bf870f9044d1.png)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 프론트에서 보내주는 정보를 DB에 담을 수 있게 되었습니다
- 유저가 담아놨던 정보를 가져올 수 있게 되었습니다
- 여러가지 TABLE을 join을 통해 프론트가 원하는 정보를 보낼수 있게 되었습니다.

2023-05-07 07:46 UTC, kyeongraekim reviewed
- order 만을 올려서 다시 재푸시해주세요!

2023-05-09 01:28 UTC, kyeongraekim requested changes

2023-05-09 01:28 UTC, kyeongraekim commented on models/orderDao.js
> +    throw err;
- 해당 내용은 각기 다른 테이블을 다른 시점에 접근하고 있기 때문에 typeORM에서 제공하는 transaction 메소드를 사용하여서 데이터 무결성을 확보해주셔야 합니다.
- 다음의 공식문서를 보고 참고해주세요!  [ 링크 바로가기](https://orkhan.gitbook.io/typeorm/docs/transactions)

2023-05-09 01:28 UTC, kyeongraekim commented on models/orderDao.js
> +      [1, user.id, orderItemsResult.insertId]
- 현재 1번이라는 숫자가 하드 코딩 되어 있습니다. 이는 웹개발에서 지양해주셔야 하는 코딩 방법입니다.
- 따라서 utils 라는 공통 활용 가능 폴더에 OrderStatusEnum을 선언하여, 1번 value를 key 값에 설정해주세요! 이를 통해 숫자 1을, 마치 변수와 같은 상수 값을 대입할 수 있도록 설정해주세요.
- 해당 관련 예시는 다음과 같습니다. 아래 워딩은 그저 예시이니 참고하여 여러분의 내용에 맞게 설정해주세요!

```javascript
const OrderStatusEnum = Object.freeze({
    PENDING : 1,
    IN_TRANSIT : 2
})

2023-05-09 06:39 UTC, msj102525 commented on models/orderDao.js
> +      [1, user.id, orderItemsResult.insertId]
이 부분은 default값으로 들어가기로 수정되어서 삭제 하면 될 거 같습니다. 다음 부터는 하드코딩 대신 밖으로 빼서 사용 하겠습니답

2023-05-10 01:56 UTC, kyeongraekim requested changes

2023-05-10 01:56 UTC, kyeongraekim commented on controllers/orderController.js
> +  return res.status(200).json(renameResult);
```suggestion
  const cartList = await orderService.getCart(user);
  if (!cartItemsByUserId) {
    error = new Error("GET_CART_CONTROLLER_ERROR");
    error.statusCode = 400;
    throw error;
  }
  const parsedCartList = cartList.map((singleCartItem) => ({
    userId: singleCartItem.user_id,
    orderItemsId: singleCartItem.order_items_id,
    orderItemsId: singleCartItem.id,
    orderPrice: singleCartItem.order_price,
    orderCount: singleCartItem.order_count,
    foodId: singleCartItem.food_id,
    food: singleCartItem.food,
    engFood: singleCartItem.eng_food,
    countryId: singleCartItem.country_id,
    country: singleCartItem.country,
    continent: singleCartItem.eng_continent,
  }));
  return res.status(200).json(renameResult);
```

2023-05-10 01:56 UTC, kyeongraekim commented on controllers/orderController.js
> +  return res.status(200).json(renameResult);
- 위와 같이 변수명 관리를 깔끔하게 해주세요! 웹 개발에서 el과 같은 불필요한 영어의 축약은 최대한 삼가해주세요!

2023-05-10 01:56 UTC, kyeongraekim commented on controllers/orderController.js
> +  return res.status(200).json(renameResult);
- 또한 위와 같은 snake -> camel case로의 변환은 mysql 선에서 충분히 이루어질 수 있다는 점을 말씀드립니다! 고민해주시고 mysql 에서 데이터를 추출할 때 부터 camelCase로 변환하여 들고오는 모습으로 바꾸어주세요!

2023-05-10 05:07 UTC, kyeongraekim approved these changes

2023-05-10 05:07 UTC, merged