[45기 TRES-문승종] login/ getCountriesList/ email, password validationCheck
wecode-bootcamp-korea/45-1st-TRES-backend pull request #9
Opened 2023-05-04 08:52 UTC by msj102525

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 로그인을 성공한 유저에게 토큰 발급 후 정보를 가진 채 페이지 이동 가능

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.
- 처음 로그인을 하거나 회원가입을 원한 유저에게 email정보를 받아 저희가 정한 형식에 맞는 email인지 확인 후 회원 유무 확인
- 회원가입한 유저일 경우 -> password입력란 생성 -> true 로그인 성공 토큰발송/ false -> 다시 입력
- 회원가입을 하지 않은 유저일 경우 -> 회원가입으로 이동 동시에 countryList 가져온후 회원가입 선호나라 선택란에 저장 -> value 통과시 회원정보 등록 후 main이동/ false 

email: id == email  유효성 검사 Eng,@, “.” 1개 , “.”앞뒤에 최소글자 2개
pw 유효성 검사 / 8자이상, 대소문자, 숫자, 특수문자 1개이상
<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
![getCountries](https://user-images.githubusercontent.com/95277177/236156289-2d14f42d-cf8e-4b43-9d9a-3aea9f893094.png)
![login_false](https://user-images.githubusercontent.com/95277177/236156339-c6e3b0fb-cacf-45e8-be18-c2a963dcfa83.png)
![login_success](https://user-images.githubusercontent.com/95277177/236156353-d6416b12-7315-4dde-8ff6-c23905c99d0f.png)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

로그인이 어떻게 작동하고 토큰을 이해했음

2023-05-05 03:33 UTC, kyeongraekim requested changes
- 불필요한 주석과 콘솔로깅을 삭제해주시고 상세 내역을 전반적으로 수정해주시고 재 푸시해주세요!

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +      // return console.log('EMAIL_NOT_FOUND!');
- 불필요한 콘솔로깅은 main 브랜치로의 푸시 전에 꼭 삭제해주시는 습관을 들여주세요!

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +    if (result === undefined) {
- 가독성을 위해서 if (!result) 의 흐름으로 부정형을 적어보시는 것은 어떠실까요?

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +    console.log(err);
- 이곳도 콘솔로깅을 삭제해주세요!

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +      return res.status(400).send(false);
- 이메일이 없을 때 보내주시는 내용은 단순 false  가 아닌 클라이언트/프론트엔드에서도 최소한의 내용을 유추할 수 있게 메세지를 담아서 보내주세요! 해당 내용은 key_error에 대한 내용이겠네요!

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +    // return console.log('EMAIL_FOUND!');
- 불필요한 주석을 삭제해주세요!

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +    err.statusCode = 400;
- 지금 유저 컨트롤러 전반에 걸쳐서 key_error를 catch 문에 들어오는 모든 에러로 수렴시키고 있습니다.
- 에러가 났을 때 키에러가 아니라면 발생할 수 있는 경우의 수가 있을 수 있음을 고려해주세요!

2023-05-05 03:33 UTC, kyeongraekim commented on controllers/userController.js
> +const joinOk = async (req, res) => {
- 저번에 구두로 전달해주신 것 처럼 함수를 담을 변수명은 CRUD의 기능이 드러난 모습으로 작성해주셔야 합니다. 해당 내용 수정해주세요!

2023-05-06 09:17 UTC, kyeongraekim requested changes

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/orderController.js
> +const getOrder = async (req, res) => {
- getOrder라는 함수 Try-Catch 문안에 정상 코드를 동작시켜야 하는 try 문이 비어있습니다. 코드를 꼼꼼히 살펴서 푸시해주시는 습관을 길러주세요!

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +    console.log(err);
- 해당 내용 반영이 되지 않았네요!

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +const getCountriesList = async (req, res) => {
- 현재 로그인, 회원가입에 해당되는 내용만 푸시가 되어야 하는데, order 내용이 잘못 같이 올라와있네요!

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +const getCountriesList = async (req, res) => {
- 개발자에게 엄격하게 깃헙 브랜치 관리하는 것은 매우 중요한 기초 소양입니다. 따라서 order관련 내용을 모두 제외하고 로그인/회원가입만 포함된 API 코드만을 올려주세요!

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +    err.statusCode = 400;
```suggestion
  } catch (err) {
    err = new Error('INVALID_USER_INPUT');
    err.statusCode = 400;
```

- 위와 같이 컨트롤러단에서 나는 에러의 포괄적인 원인을 에러메세지에 담아도 좋겠네요!

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +      return res.status(400).send(false);
```suggestion
    if (!email || !password) {
      return res.status(400).json({ message: Key_Error });
```

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +    return res.status(200).json({ message: '회원가입 성공!' });
- 해당 json 메세지는 실제 사용하는 유저가 아닌 클라이언트/프론트엔드에서 확인하는 메세지입니다. 따라서 사용자가 확인할 법한 메세징이 아닌 개발자가 확인할 법한, 해당 메시지를 통해서 이후의 로직을 이어나갈 수 있을 법한 메세지의 내용으로 수정해주세요!

2023-05-06 09:17 UTC, kyeongraekim commented on controllers/userController.js
> +    return res.status(200).json({ message: '회원가입 성공!' });
```suggestion
    return res.status(200).json({ message: 'SUCCESS' });
```

2023-05-06 09:17 UTC, kyeongraekim commented on models/userDao.js
> +    ORDER BY country;
```suggestion
    SELECT 
     id, 
     country
    FROM
    countries
    ORDER BY country;
```

2023-05-06 09:17 UTC, kyeongraekim commented on models/userDao.js
> +const signUp = async (email, firstName, lastName, password, countries, pNumber, gender, birth, address) => {
- 현재 인자값으로 받아오는 변수명이 매우 모호합니다. 
- pNumber가 아닌, phoneNumber와 같이 영어 원어를 풀어써서 가독성을 높여주세요!

2023-05-06 09:17 UTC, kyeongraekim commented on routes/userRouter.js
> +router.post('/check', userController.userEmailCheck);
- RESTful 한 엔드포인트 설계에 맞게 check의 내용을 email-check 정도로 명확하게 표현하여 어떠한 리소스적 행위가 가미되어 있는지 표현해주세요!

2023-05-06 09:17 UTC, kyeongraekim commented on services/userService.js
> +        issuer: 'inni',
- 해당 내용은 jwt 토큰을 만드는데 중요한 보안에 민감한 정보들이니, 환경변수에 담아서 관리해주세요!

2023-05-06 09:17 UTC, kyeongraekim commented on utils/authorization.js
> +    console.log(`token`, token);
- 불필요한 콘솔로그를 모두 지워주세요!

2023-05-06 09:27 UTC, msj102525 commented on controllers/userController.js
> +const getCountriesList = async (req, res) => {
회원가입시 필요한 함수입니다 DB에 저장되어 있는 나라들을 회원가입시 선호 나라를 선택할 수 있게 도와주는 api입니다

2023-05-07 01:50 UTC, kyeongraekim requested changes

2023-05-07 01:50 UTC, kyeongraekim commented on controllers/userController.js
> +    return res.status(200).json({ message: '회원가입 성공!' });
- 해당 부분이 아직 미반영 상태인 거서 같네요! 메세지가 다른 곳은 영문, 이곳은 한국어로 되어 있는게 이질적이며, 다시 한 번 클라이언트가 활용할 메세지로서 구조화 시켜주시는 것을 권장드립니다.

2023-05-07 07:41 UTC, kyeongraekim approved these changes

2023-05-07 07:41 UTC, kyeongraekim approved these changes

2023-05-07 08:28 UTC, merged